hashthat/hashthat/urls.py
from django.contrib import admin
from django.urls import path
from hashing import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('hash/<str:hash>', views.hash, name='hash'),
    path('quickhash', views.quickhash, name='quickhash'),
]

hashthat/hashing/models.py
from django.db import models

# Create your models here.
class Hash(models.Model):
    text = models.TextField()
    hash = models.CharField(max_length=64)

hashthat/hashing/forms.py
from django import forms

class HashForm(forms.Form):
    text = forms.CharField(label='Enter hash here:', widget=forms.Textarea )

hashthat/hashing/views.py
from django.shortcuts import redirect, render
from .forms import HashForm
from .models import Hash
import hashlib
from django.http import JsonResponse

def home(request):
    if request.method == 'POST':
        filled_form = HashForm(request.POST)
        if filled_form.is_valid():
            text = filled_form.cleaned_data['text']
            text_hash = hashlib.sha256(text.encode('utf-8')).hexdigest()
            try:
                Hash.objects.get(hash=text_hash)
            except Hash.DoesNotExist:
                hash = Hash()
                hash.text = text
                hash.hash = text_hash
                hash.save()
            return redirect('hash',hash=text_hash)

    form = HashForm()
    return render(request, 'hashing/home.html', {'form': form})

def hash(request, hash):
    hash = Hash.objects.get(hash=hash)
    return render(request, 'hashing/hash.html', {'hash': hash})

def quickhash(request):
    text = request.GET['text']
    return JsonResponse({'hash': hashlib.sha256(text.encode('utf-8')).hexdigest()})

hashthat/hashing/templates/hashing/hash.html
<h2>Hash:</h2>
<h1>{{ hash.hash }}</h1>
<h2>Text:</h2>
{{ hash.text }}
<h3><a href="{% url 'home' %}">Home</a></h3>

hashthat/hashing/templates/hashing/home.html
<form action="{% url 'home' %}" method="post">
    {% csrf_token %}
    {{form.as_p }}
    <input name="submit" type="submit" value="Hash">
</form>

<h2 id="quickhash"></h2>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script>
    $('#id_text').keyup(function () {
      var text = $(this).val();


      $.ajax({
        url: '/quickhash',
        data: {
          'text': text
        },
        dataType: 'json',
        success: function (data) {
          $('#quickhash').text(data['hash']);
        }
      });


    });
  </script>